language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
- npm run bundleIos
- npm run zipIos
- npm run bundleAndroid
- npm run zipAndroid
- npm run upload
deploy:
  provider: releases
  file:
  - bundle.ios.zip
  - bundle.android.zip
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure hY13P503ZoN7TWBRMrDIWg
